### PR TITLE
Update the pytest plugin to be compatible with v2 of the API client

### PR DESCRIPTION
**Pull request by rsnyman**
Depends on https://github.com/ibutsu/ibutsu-client-python/pull/13 being merged and a new release created.

### CODE REVIEW

**Comment by john-dupuy** [comment]
@rsnyman I am seeing the following error when running this locally: 
```
INTERNALERROR>   File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-client-python/ibutsu_client/model_utils.py", line 1276, in attempt_convert_item
INTERNALERROR>     raise get_type_error(input_value, path_to_item, valid_classes,
INTERNALERROR> ibutsu_client.exceptions.ApiTypeError: Invalid type for variable 'start_time'. Required value type is str and passed type was datetime at ['run']['start_time']
```

**Comment by rsnyman** [comment]
> @rsnyman I am seeing the following error when running this locally, I'm not sure why this isn't being autoconverted:
> 
> ```
> INTERNALERROR>   File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-client-python/ibutsu_client/model_utils.py", line 1276, in attempt_convert_item
> INTERNALERROR>     raise get_type_error(input_value, path_to_item, valid_classes,
> INTERNALERROR> ibutsu_client.exceptions.ApiTypeError: Invalid type for variable 'start_time'. Required value type is str and passed type was datetime at ['run']['start_time']
> ```

I'll take a look, thanks.

**Comment by rsnyman** [comment]
Do you want to try again? Make sure you use https://github.com/ibutsu/ibutsu-client-python/pull/13

**Comment by john-dupuy** [comment]
```
INTERNALERROR>   File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-client-python/ibutsu_client/model_utils.py", line 1394, in validate_and_convert_types
INTERNALERROR>     converted_instance = attempt_convert_item(
INTERNALERROR>   File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-client-python/ibutsu_client/model_utils.py", line 1281, in attempt_convert_item
INTERNALERROR>     return deserialize_model(input_value, valid_class,
INTERNALERROR>   File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-client-python/ibutsu_client/model_utils.py", line 1201, in deserialize_model
INTERNALERROR>     return model_class(**kw_args)
INTERNALERROR>   File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-client-python/ibutsu_client/model_utils.py", line 1566, in wrapped_init
INTERNALERROR>     return fn(self, *args, **kwargs)
INTERNALERROR>   File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-client-python/ibutsu_client/model/result.py", line 200, in __init__
INTERNALERROR>     setattr(self, var_name, var_value)
INTERNALERROR>   File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-client-python/ibutsu_client/model_utils.py", line 167, in __setattr__
INTERNALERROR>     self[attr] = value
INTERNALERROR>   File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-client-python/ibutsu_client/model_utils.py", line 352, in __setitem__
INTERNALERROR>     self.set_attribute(name, value)
INTERNALERROR>   File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-client-python/ibutsu_client/model_utils.py", line 116, in set_attribute
INTERNALERROR>     raise ApiAttributeError(
INTERNALERROR> ibutsu_client.exceptions.ApiAttributeError: Result has no attribute 'component' at ['received_data']['component']
```
Looks like we need to add `component` as an attribute in the OpenAPI spec?

**Review by john-dupuy — APPROVED** [review]

**Pull request merged**
