### PR TITLE
Created a python package

### PR DESCRIPTION
**Pull request by quarckster**

### CODE REVIEW

**Review by john-dupuy — APPROVED** [review]

**Review by john-dupuy — COMMENTED** [review]
@quarckster running this locally with a command like 
```
ENV_FOR_DYNACONF=stage_proxy iqe tests plugin rbac -m core --ibutsu $IBUTSU_BE
```

```console
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --ibutsu --ibutsu-project insights-qe
  inifile: None
  rootdir: /home/jdupuy/iqe/iqe-repos/ibutsu/pytest-ibutsu
```

**Review by john-dupuy — CHANGES_REQUESTED** [review]
Args aren't being picked up by `pytest`

**Comment by quarckster** [comment]
@john-dupuy thanks for checking. I fixed `entrypoints.txt`.

**Comment by john-dupuy** [comment]
@quarckster now I can see the args when I do `pytest --help` but it looks like this is still incompatible with iqe-core. I'm still seeing that same error with the command I pasted above.

**Comment by john-dupuy** [comment]
@quarckster sorry for the false positive, my local env had some cached things - clearing that up and re-installing, it's now working.

**Review by john-dupuy — APPROVED** [review]

**Review by rsnyman — APPROVED** [review]
Looks good. I would have renamed the pytest_ibutsu file, but that's something we can do at a later stage.

**Pull request merged**
